version: '3'
services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - shared_mysql_data:/var/lib/mysql
      - ./scripts/db:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - shared_redis_data:/data

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - shared_minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  shared_mysql_data:
    external: true
  shared_redis_data:
    external: true
  shared_minio_data:
    external: true
